name: Angular GitHub CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./addMusic
        run: npm install

      - name: Build
        working-directory: ./addMusic
        run: npm run build      
        
      - name: Zip file
        working-directory: ./addMusic
        uses: montudor/action-zip@v1
        with:
        args: zip -qq -r addMusic.zip dist/addMusic

      - name: Upload artifact
        working-directory: ./addMusic
        uses: actions/upload-artifact@v2
        with:
          name: addMusic.zip
