name: Angular GitHub CI
on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./addMusic
        run: npm install

      - name: Build
        working-directory: ./addMusic
        run: npm run build      

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addMusic.zip addMusic/dist/addMusic/

      - name: list dir
        run: ls
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          release_name: 'test'
          tag_name: ${{ github.ref }}
          files: addMusic.zip
          
          
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        working-directory: ./server
        run: mvn -B package --file pom.xml

  
