name: Angular GitHub CI
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  set-up:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  frontend-build:
    needs: [set-up]
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./addMusic
        run: npm install

      - name: Build
        working-directory: ./addMusic
        run: npm run build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addMusic.zip addMusic/dist/addMusic/


  backend-build:
    needs: [set-up]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        working-directory: ./server
        run: mvn -B package --file pom.xml

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r backend.zip server/target/quarkus-app/



  release:
    needs: [frontend-build, backend-build]
    runs-on: ubuntu-latest

    steps:
    - name: Release server
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        release_name: 'test'
        tag_name: 'v0.0.2'
        files: |
          addMusic.zip
          backend.zip
          server/artists.csv
